export const ROUTES = {
  DASHBOARD: '/',
  BA_DASHBOARD: '/ba-dashboard',
  RA_DASHBOARD: '/ra-dashboard',
  UX_DASHBOARD: '/ux-dashboard',
  TENANTS: '/tenants',
  TENANTS_NEW: '/tenants/new',
  TENANT_DETAIL: '/tenants/:id',
  PROJECTS: '/projects',
  PROJECTS_NEW: '/projects/new',
  PROJECT_DETAIL: '/projects/:id',
  PROJECT_EDIT: '/projects/:id/edit',
  PROJECT_KICKOFF: '/projects/kickoff',
  PROJECT_KICKOFF_DETAIL: '/projects/kickoff/:projectId',
  BLUEPRINTS: '/blueprints',
  AGENTS: '/agents',
  AGENT_DETAIL: '/agents/:id',
  PIPELINES: '/pipelines',
  USERS: '/users',
  PROFILE: '/profile',
  CHATBOT: '/chatbot',
  SETTINGS: '/settings',
} as const

export type RoutePath = (typeof ROUTES)[keyof typeof ROUTES]
